plugins {
    id 'java'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
    id 'net.minecraftforge.jarjar' version '0.2.3'
}

version = mod_version
group = mod_group_id

//base {
//    archivesName = "TurnBasedMinecraft-Forge"
//}

// Mojang ships Java 25 to end users in 26.1+, so your mod should target Java 25.
java.toolchain.languageVersion = JavaLanguageVersion.of(25)
println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"
// Include generated resources

sourceSets.main.resources { srcDir 'src/generated/resources' }

jarJar.register()

tasks.named('jar') {
    archiveClassifier = null
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : mod_authors,
            'Specification-Version'   : '1', // We are version 1 of ourselves
            'Implementation-Title'    : "TurnBasedMinecraftMod",
            'Implementation-Version'  : project.jar.archiveVersion,
            'Implementation-Vendor'   : mod_authors
        ])
    }
}
tasks.named('jarJar') {
    archiveClassifier = null
}

minecraft {
    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')

            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'
            systemProperty 'forge.enabledGameTestNamespaces', mod_name
        }

        register('client')

        register('server') {
            args '--nogui'
        }

        register('gameTestServer')

        register('data') {
            workingDir = layout.projectDirectory.dir('run-data')

            args '--mod', 'examplemod', '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

repositories {
    minecraft.mavenizer(it) // In Kotlin, it = this
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()

    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    flatDir {
        dir 'libs'
    }
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:26.1.2-64.0.4')
    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'


    implementation 'fr.delthas:javamp3:1.0.3'

    implementation 'com.github.stephengold:j-ogg-vorbis:1.0.4'

    jarJar('fr.delthas:javamp3:1.0.3')
    jarJar('com.github.stephengold:j-ogg-vorbis:1.0.4')

    //jarJar(group: 'fr.delthas', name: 'javamp3', version: '[1.0.0,2.0.0)') {
    //    jarJar.configure(it, '1.0.3')
    //}

    //jarJar(group: 'com.github.stephengold', name: 'j-ogg-vorbis', version: '[1.0.4, 2.0.0)') {
    //    jarJar.configure(it, '1.0.4')
    //}
}

// This block of code expands all declared replace properties in the specified resource targets.
// A missing property will result in an error. Properties are expanded using ${} Groovy notation.
// When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
// See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
//tasks.named('processResources', ProcessResources) {
//    var replaceProperties = [
//            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
//            forge_version: forge_version, forge_version_range: forge_version_range,
//            loader_version_range: loader_version_range,
//            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
//            mod_authors: mod_authors, mod_description: mod_description,
//    ]
//    inputs.property('replaceProperties', replaceProperties)
//
//    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
//        expand replaceProperties
//    }
//}

// Reproducible Builds
tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// Ensure "jarJar" is run after "build"
//tasks.named("build").configure {
//    finalizedBy "jarJar"
//}
